; Robot Piscina — firmware ESP32
; Build:   pio run
; Upload:  pio run -t upload
; Filesys: pio run -t uploadfs   (carica la cartella data/ in LittleFS)
; Monitor: pio device monitor -b 115200

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    links2004/WebSockets @ ^2.4.1
    pololu/VL53L0X @ ^1.3.1

build_flags =
    -DCORE_DEBUG_LEVEL=2
